### ISSUE TITLE
[Question] Is it possible to detect barcode in an image?

### ISSUE THREAD

**Issue by Udbhav12** [zsajjad/react-native-text-detector#14]
react-native-text-detector allows us to detect text in a static image.

My use case is to detect barcode also in that static image. Is it possible to do so ?

**Comment by zsajjad** [comment]
This package doesn't do this ATM.
We're working on similar thing but it's not ready for iOS as of now. Check it out

https://gitlab.com/fetchsky/react-native-image-qr

**Comment by Udbhav12** [comment]
@zsajjad - I need it for android only as of now.Is it working for android ?
