### ISSUE TITLE
Execution failed for task ':react-native-text-detector:verifyReleaseResources'

### ISSUE THREAD

**Issue by jairrc** [zsajjad/react-native-text-detector#20]
**Execution failed for task ':react-native-text-detector:verifyReleaseResources'**

I'm trying to generate the APK file and when it reaches 96%, this error, below, occurs. I could not find a solution and I need to urgently generate the update of the App. Has anyone gone through this and can point out a possible solution?

- **My versions**

Android Studio version: 3.4
Gradle version: 5.1.1
react-native-cli: 2.0.1
react-native: 0.55.4
npm: 6.9.0

- **In my android/build.gradle I have:**

dependencies {
    classpath 'com.android.tools.build:gradle:3.4.0'
    classpath 'com.google.gms:google-services:4.1.0'
    classpath 'com.bugsnag:bugsnag-android-gradle-plugin:4.+'
}

ext {
    buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 28
    targetSdkVersion = 28
    supportLibVersion = '26.1.0'
    googlePlayServicesVersion = "16.+"
    firebaseVersion = "17.6.0"    
}

- **In my ./app/build.gradle file, I have:**

 compileSdkVersion rootProject.ext.compileSdkVersion
 buildToolsVersion '27.0.3'
 defaultConfig {
     applicationId "com.rvm"
     minSdkVersion rootProject.ext.minSdkVersion
     targetSdkVersion rootProject.ext.targetSdkVersion
     versionCode 1
     versionName "1.0"
     multiDexEnabled true
     ndk {
         abiFilters "armeabi-v7a", "x86"
     }
...
}

------------------------------------------------------------
**### The error:**

> Task :react-native-text-detector:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-text-detector:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  D:\src\RN\rn_rvm\node_modules\react-native-text-detector\android\build\intermediates\res\merged\release\values\values.xml:1785: error: resource android:attr/fontVariationSettings not found.
  D:\src\RN\rn_rvm\node_modules\react-native-text-detector\android\build\intermediates\res\merged\release\values\values.xml:1786: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by jairrc** [comment]
I was able to generate my APK by making the following changes in the build.gradle file of the react-native-text-detector, in the path bellow:

**node_modules\react-native-text-detector\android**

**//ORIGINAL**
// android {
//    compileSdkVersion 27
//    buildToolsVersion "23.0.1"
// 
//    defaultConfig {
//        minSdkVersion 16
//        targetSdkVersion 27
//        versionCode 1
//        versionName "1.0"
//    }
//    lintOptions {
//        abortOnError false
//    }
// }

**//NEW**
 android {
     compileSdkVersion 28
 		buildToolsVersion "28.0.3"
     defaultConfig {
         minSdkVersion 16
         targetSdkVersion 28
         versionCode 1
         versionName "1.0"
     }
     lintOptions {
         abortOnError false
     }
 }

**Comment by hammooooody** [comment]
Thank you sir! @jairrc
