### ISSUE TITLE
detectFromUri works fine in android but it returns false in iOS

### ISSUE THREAD

**Issue by haison8x** [zsajjad/react-native-text-detector#28]
I used  https://github.com/jeanpan/react-native-camera-roll-picker#readme to get the image from photo library, it returned uri: ph://11A68DD6-A651-462D-BDAB-68FB853ED141/L0/001

Unfortunately, detectFromUri  always returns false and show the following error in console:
NSURLConnection finished with error - code -1002

However, the Image Control can show the image with that uri .

Here is my source code : https://github.com/haison8x/react-native-test-ocr

**Comment by haison8x** [comment]
I have posted the solution here

https://stackoverflow.com/questions/59726747/react-native-text-detector-worked-fine-in-android-but-why-it-always-returned-fal

**Comment by uranashel95** [comment]
No. 
This library works. Your is not work. 👎 
You can double check.
