### ISSUE TITLE
RNTextDetectorModule

### ISSUE THREAD

**Issue by kashifJawed90** [zsajjad/react-native-text-detector#5]
![whatsapp image 2018-10-06 at 3 00 38 am](https://user-images.githubusercontent.com/16566190/46563553-88218c00-c91b-11e8-80e8-fa7f102a4318.jpeg)

Hi, 
I tried to implement this but not working at my end.
To replicate:

react-native init myApp then cd myApp.
npm install react-native-text-detector --save

It seems it happened in the file RNTextDetectorModule.java in line 51.

 Task<FirebaseVisionText> result =
 line 51:                   this.detector.processImage(image)

**Comment by zsajjad** [comment]
This package uses firebase ML Kit on Android and TesseractOCR on iOS. For android please make sure you have integrated firebase properly.
Here is the guide for doing this.

https://firebase.google.com/docs/android/setup

**Comment by kashifJawed90** [comment]
Thanks resolved !
-I created a project on firebase console with package name "com.businessCard" (replace it with your own package name)
-added google-services.json file inside android/src/
- In the android/app/build.gradle(app) add line at the end : apply plugin: 'com.google.gms.google-services'
