### ISSUE TITLE
Android app crashes on startup: com.google.android.gms.internal.zzdls not found

### ISSUE THREAD

**Issue by SimoneMSR** [zsajjad/react-native-text-detector#6]
I have followed the instruction in the README.md, added the `google-services.json` file.
When I run my app, I can see from the Android Studio debugger this error:

```
E/AndroidRuntime: FATAL EXCEPTION: FirebaseMLHandler
                  Process: com.businesscards, PID: 17600
                  java.lang.NoClassDefFoundError: com.google.android.gms.internal.zzdls
```
And the app just crashes. I have googled the error, cleaned and rebuild the project, but the error is still there. What's happening?
Could that be the gradle version?

my package.json contains
```
...
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-camera": "^1.2.0",
    "react-native-text-detector": "^0.0.5"
  },
...
```
I use 
- com.android.tools.build:gradle:3.1.3 and
- Android SDK Build Tools 27.0.3

**Comment by zsajjad** [comment]
This package uses Firebase ML Kit for text recognition on android please make sure you have integrated firebase in your app before started integration of this package. [Here is the guide](https://firebase.google.com/docs/android/setup) for Firebase integration.

**Comment by SimoneMSR** [comment]
Thank you @zsajjad  for your hint. But the problem was elsewhere, with the [react-nativa-camera](https://github.com/react-native-community/react-native-camera) module that I was using.-
Following [this](https://github.com/react-native-community/react-native-camera/issues/1530#issuecomment-399381409) issue post, I was trying to use react-native-camera with your react-native-text-detector.
The solution hinted by the community lead me to the error I wrote before. I solved the problem by changing some configuration in my gradle conf files.
Now this is working!

**Comment by zsajjad** [comment]
Happy that you are out of trouble.

**Comment by Ali-Ayyad** [comment]
@SimoneMSR can you share what changes did you do to the gradle conf files ? Having the same problem

**Comment by SimoneMSR** [comment]
@Ali-Ayyad , I have applied [these ](https://github.com/react-native-community/react-native-camera/issues/1530#issuecomment-399381409)changes
